import type { Asambleista, Candidato, Categoria } from "./types"

export const categorias: Categoria[] = [
  "Docentes Principales",
  "Docentes Asociados",
  "Docentes Auxiliares",
  "Estudiantes",
]

export const asambleistasIniciales: Asambleista[] = [
  { id: "1", nombre: "Juan Pérez", haVotado: false },
  { id: "2", nombre: "María López", haVotado: false },
  { id: "3", nombre: "Carlos Rodríguez", haVotado: false },
  { id: "4", nombre: "Ana Martínez", haVotado: false },
  { id: "5", nombre: "Pedro Sánchez", haVotado: false },
  { id: "6", nombre: "Laura García", haVotado: false },
  { id: "7", nombre: "Miguel Fernández", haVotado: false },
  { id: "8", nombre: "Sofía Torres", haVotado: false },
]

export const candidatosIniciales: Candidato[] = [
  // Docentes Principales
  {
    id: "dp1",
    nombre: "Roberto Gómez",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "05",
  },
  {
    id: "dp2",
    nombre: "Carmen Jiménez",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "12",
  },
  {
    id: "dp3",
    nombre: "Francisco Ruiz",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "08",
  },
  {
    id: "dp4",
    nombre: "Luisa Morales",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "03",
  },
  {
    id: "dp5",
    nombre: "Antonio Vega",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "15",
  },
  {
    id: "dp6",
    nombre: "Antonio Vega",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "15",
  },
  {
    id: "dp7",
    nombre: "Antonio Cruz",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "20",
  },
  {
    id: "dp8",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  {
    id: "dp9",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  {
    id: "dp10",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  {
    id: "dp11",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  {
    id: "dp12",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  {
    id: "dp13",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },
  {
    id: "dp14",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },
  {
    id: "dp15",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },
  {
    id: "dp16",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },
  {
    id: "dp17",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  {
    id: "dp18",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  {
    id: "dp19",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  {
    id: "dp20",
    nombre: "Frank Torres",
    categoria: "Docentes Principales",
    votos: 0,
    codigoFacultad: "21",
  },

  // Docentes Asociados
  {
    id: "da1",
    nombre: "Elena Morales",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "07",
  },
  {
    id: "da2",
    nombre: "Javier Ortega",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "19",
  },
  {
    id: "da3",
    nombre: "Lucía Navarro",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "01",
  },
  {
    id: "da4",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "01",
  },
  {
    id: "da5",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da6",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da7",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da8",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da9",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da10",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da11",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da12",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da13",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da14",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da15",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },
  {
    id: "da16",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },

  {
    id: "da17",
    nombre: "Martín Soto",
    categoria: "Docentes Asociados",
    votos: 0,
    codigoFacultad: "10",
  },

  // Docentes Auxiliares
  {
    id: "dau1",
    nombre: "Raúl Molina",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "14",
  },
  {
    id: "dau2",
    nombre: "Beatriz Castro",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "06",
  },
  {
    id: "dau3",
    nombre: "Daniel Herrera",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "11",
  },
  {
    id: "dau4",
    nombre: "Raúl Molina",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "14",
  },
  {
    id: "dau5",
    nombre: "Beatriz Castro",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "06",
  },
  {
    id: "dau6",
    nombre: "Daniel Herrera",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "11",
  },
  {
    id: "dau7",
    nombre: "Raúl Molina",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "14",
  },
  {
    id: "dau8",
    nombre: "Beatriz Castro",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "06",
  },
  {
    id: "dau9",
    nombre: "Daniel Herrera",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "11",
  },
  {
    id: "dau10",
    nombre: "Raúl Molina",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "14",
  },
  {
    id: "dau11",
    nombre: "Beatriz Castro",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "06",
  },
  {
    id: "dau12",
    nombre: "Daniel Herrera",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "11",
  },
  {
    id: "dau13",
    nombre: "Raúl Molina",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "14",
  },
  {
    id: "dau14",
    nombre: "Beatriz Castro",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "06",
  },
  {
    id: "dau15",
    nombre: "Daniel Herrera",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "11",
  },
  {
    id: "dau16",
    nombre: "Raúl Molina",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "14",
  },
  {
    id: "dau17",
    nombre: "Beatriz Castro",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "06",
  },
  {
    id: "dau18",
    nombre: "Daniel Herrera",
    categoria: "Docentes Auxiliares",
    votos: 0,
    codigoFacultad: "11",
  },

  // Estudiantes
  {
    id: "e1",
    nombre: "Alejandro Vargas",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "02",
  },
  {
    id: "e2",
    nombre: "Natalia Reyes",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "09",
  },
  {
    id: "e3",
    nombre: "Pablo Mendoza",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "16",
  },
  {
    id: "e4",
    nombre: "Valeria Campos",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "04",
  },
  {
    id: "e5",
    nombre: "Gabriel Torres",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "18",
  },
  {
    id: "e6",
    nombre: "Alejandro Vargas",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "02",
  },
  {
    id: "e7",
    nombre: "Natalia Reyes",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "09",
  },
  {
    id: "e8",
    nombre: "Pablo Mendoza",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "16",
  },
  {
    id: "e9",
    nombre: "Valeria Campos",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "04",
  },
  {
    id: "e10",
    nombre: "Gabriel Torres",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "18",
  },
  {
    id: "e11",
    nombre: "Alejandro Vargas",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "02",
  },
  {
    id: "e12",
    nombre: "Natalia Reyes",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "09",
  },
  {
    id: "e13",
    nombre: "Pablo Mendoza",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "16",
  },
  {
    id: "e14",
    nombre: "Valeria Campos",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "04",
  },
  {
    id: "e15",
    nombre: "Gabriel Torres",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "18",
  },
  {
    id: "e16",
    nombre: "Alejandro Vargas",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "02",
  },
  {
    id: "e17",
    nombre: "Natalia Reyes",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "09",
  },
  {
    id: "e18",
    nombre: "Pablo Mendoza",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "16",
  },
  {
    id: "e19",
    nombre: "Valeria Campos",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "04",
  },
  {
    id: "e20",
    nombre: "Gabriel Torres",
    categoria: "Estudiantes",
    votos: 0,
    codigoFacultad: "18",
  },
];
